[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan storage:link --force && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"

# MySQL Configuration
[env]
MYSQL_MODE = "NO_AUTO_VALUE_ON_ZERO,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
APP_URL = "https://web-production-4859.up.railway.app"
APP_ENV = "production"
APP_DEBUG = "false"